# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/astaxie/beego"
  revision = "f16688817aa428d10361394015b40d096b680542"

[[constraint]]
  name = "github.com/davyxu/cellnet"
  revision = "21401baf4f72ce883c746868fbffade45c90f40d"

[[constraint]]
  name = "github.com/davyxu/golog"
  revision = "e51e2504138b41957f9a1b1a50dc1b10ad33cd1d"

[[constraint]]
  name = "github.com/globalsign/mgo"
  revision = "f76e4f9da92ecd56e3be26f5ba92580af1ef97b4"

[[constraint]]
  name = "github.com/go-redis/redis"
  revision = "877867d2845fbaf86798befe410b6ceb6f5c29a3"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  revision = "749ddf1598b47e3cd909414bda735fe790ef3d30"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "30cf7ac33676b5786e78c746683f0d4cd64fa75b"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  revision = "0dae4fefe7c0e190f7b5a78dac28a1c82cc8d849"

[[constraint]]
  name = "github.com/robfig/cron"
  revision = "2315d5715e36303a941d907f038da7f7c44c773b"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "5420a8b6744d3b0345ab293f6fcba19c978f1183"

[[constraint]]
  name = "github.com/szyhf/go-excel"
  revision = "72be56ac2ac1caa5895d95d0e6be74ffa2281a99"

[[constraint]]
  name = "github.com/inconshreveable/mousetrap"
  revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"

[[constraint]]
  name = "github.com/looplab/fsm"
  revision = "f980bdb68a8962823200eafe6c0aa99e917be0d7"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "ef82de70bb3f60c65fb8eebacbb2d122ef517385"
  
[[constraint]]
  name = "github.com/spf13/pflag"
  revision = "583c0c0531f06d5278b7d917446061adc344b5cd"

[[override]]
  name = "github.com/davyxu/goobjfmt"
  revision = "baf5de0715b190ed9201969ad0c8a3e88e5ee004"

[[override]]
  name = "github.com/szyhf/go-convert"
  revision = "ec578202a465308f7f8f8daff1b998a9247e8de6"



[prune]
  go-tests = true
  unused-packages = true